var Entities =
{
	"ammo_9mmclip": 		{ model: "w_9mmclip.mdl" },
	"ammo_9mmAR": 			{ model: "w_9mmar.mdl" },
	"ammo_9mmbox": { model: "w_9mmarclip.mdl" },
	"ammo_ARgrenades": { model: "w_9mmarclip.mdl" },
	"ammo_buckshot": { model: "w_shotbox.mdl" },
	"ammo_357": { model: "w_357ammo.mdl" },
	"ammo_rpgclip": { model: "w_rpgammo.mdl" },
	"ammo_gaussclip": { model: "w_gaussammo.mdl" },
	"ammo_crossbow": { model: "w_crossbow_clip.mdl" },
	"env_sprite": {},
	"Item": {},
	"item_airtank": {},
	"item_antidote": {},
	"item_battery": { model: "w_battery.mdl" },
	"item_healthkit": {},
	"item_longjump": {},
	"item_suit": { model: "w_suit.mdl" },

	"monster_alien_controller": { model: "controller.mdl" },
	"monster_alien_grunt": { model: "agrunt.mdl" },
	"monster_alien_slave": {},
	"monster_apache": { model: "apache.mdl" },
	"monster_babycrab": { model: "baby_headcrab.mdl" },
	"monster_barnacle": { model: "barnacle.mdl" },
	"monster_barney": { model: "barney.mdl" },
	"monster_barney_dead": { model: "barney.mdl" },
	"monster_bigmomma": { model: "big_mom.mdl" },
	"monster_bloater": {},
	"monster_bullchicken": { model: "bullsquid.mdl" },
	"monster_cockroach": {},
	"monster_flyer-flock": { model: "aflock.mdl" },
	"monster_furniture": {},
	"monster_gargantua": { model: "garg.mdl" },
	"monster_generic": {},
	"monster_gman": { model: "gman.mdl" },
	"monster_grunt_repel": {},
	"monster_handgrenade": { model: "grenade.mdl" },
	"monster_satchelcharge": {},
	"monster_headcrab": { model: "headcrab.mdl" },
	"monster_hevsuit_dead": {},
	"monster_hrunt_dead": { model: "hgrunt.mdl" },
	"monster_houndeye": { model: "houndeye.mdl" },
	"monster_human_assassin": { model: "hassassin.mdl" },
	"monster_human_grunt": { model: "hgrunt.mdl" },
	"monster_ichthyosaur": { model: "icky.mdl" },
	"monster_leech": { model: "leech.mdl" },
	"monster_miniturret": { model: "miniturret.mdl" },
	"monster_nihilanth": { model: "nihilanth.mdl" },
	"monster_osprey": { model: "osprey.mdl" },
	"monster_rat": { model: "bigrat.mdl" },
	"monster_scientist": { model: "scientist.mdl" },
	"monster_scientist_dead": { model: "scientist.mdl" },
	"monster_sitting_scientist": { model: "scientist.mdl" },
	"monster_sentry": { model: "sentry.mdl" },
	"monster_snark": {},
	"monster_tentacle": {},
	"monster_tripmine": {},
	"monster_turret": { model: "turret.mdl" },
	"monster_zombie": { model: "zombie.mdl" },

	"weaponbox": { model: "w_weaponbox.mdl" },
	"weapon_crowbar": { model: "w_crowbar.mdl" },
	"weapon_9mmhandgun": { model: "w_9mmhandgun.mdl" },
	"weapon_357": { model: "w_357.mdl" },
	"weapon_9mmAR": { model: "w_9mmar.mdl" },
	"weapon_shotgun": { model: "w_shotgun.mdl" },
	"weapon_rpg": { model: "w_rpg.mdl" },
	"weapon_gauss": { model: "w_gauss.mdl" },
	"weapon_crossbow": { model: "w_crossbow.mdl" },
	"weapon_egon": { model: "w_egon.mdl" },
	"weapon_tripmine": {},
	"weapon_satchel": { model: "w_satchel.mdl" },
	"weapon_handgrenade": { model: "w_grenade.mdl" },
	"weapon_snark": { model: "w_sqknest.mdl" },
	"weapon_hornetgun": { model: "w_hgun.mdl" },
	"weapon_items": {},

	"xen_plantlight": { model: "light.mdl" },
	"xen_hair": { model: "hair.mdl" },
	"xen_tree": { model: "tree.mdl" },
	"xen_spore_small": {},
	"xen_spore_medium": {},
	"xen_spore_large": {}
}